name: "telegram_analytics"
version: "1.0.0"
config-version: 2

profile: "telegram_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  telegram_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
      core:
        +materialized: table

vars:
  raw_schema: raw
  staging_schema: staging
  marts_schema: marts
